version: "3.8"
services:
  dev:
    build:
      context: ./.dockerdev
      dockerfile: Dockerfile_dev
      args:
        - USER="${USER:-gradle}"
        - USERID=${USERID:-1000}
    image: ${USER:-someone}/spring-dev:latest
    stdin_open: true
    tty: true
    tmpfs:
      - /tmp
    volumes:
      - /app
      - /dotgradle
    ports:
      - 8080:8080

  builder:
    build:
      context: ./project
      dockerfile: ../.dockerdev/Dockerfile_build
      args:
        - USER="${USER:-gradle}"
        - USERID=${USERID:-1000}
    image: ${USER}/spring-build:latest
    tmpfs:
      - /tmp
    volumes:
      - /app
      - /dotgradle

  spring:
    image: ${USER}/spring-build:latest
    depends_on:
      - builder
