version: "3.8"
services:
  dev:
    build:
      dockerfile: Dockerfile
      args:
        - USER="${USER:-gradle}"
        - USERID=${USERID:-1000}
        - PROJECT="${PRJ:-./project}"
    image: spring-dev:1.0.0
    stdin_open: true
    tty: true
    tmpfs:
      - /tmp
    volumes:
      - $PROJECT:/app
    ports:
      - 8080:8080
