#! /usr/bin/env bash

if [[ $# -ne 1 ]]; then
    echo "Usage: $(basename "$0") <project path>"
    exit 2
fi

spth="$(cd "$(dirname "$0")"; pwd -P)"
projectpath="$1"

rm ${spth}/project
ln -s "$1" "${spth}/project"

USER=$(whoami) USERID=$(id -u) docker compose run --rm -p 8080:8080 -v "${spth}/project":/app -v "${spth}/project/.dockerdev/.gradle":/dotgradle dev /bin/bash
