#! /usr/bin/env bash

spth="$(cd "$(dirname "$0")"; pwd -P)"
if [[ $# -ne 1 ]]; then
    echo "Usage: $(basename "$0") <project path>"
    exit 2
fi
projectpath="$1"

USER=$(whoami) USERID=$(id -u) PRJ=${projectpath} DOTGRADLE=${projectpath}/.dockerdev/.gradle docker compose run --rm -p 8080:8080 dev /bin/bash