FROM adoptopenjdk:11-jdk-openj9-focal AS builder

ARG USER
ARG USERID

RUN apt-get update -qq && \
  DEBIAN_FRONTEND=noninteractive apt-get -yq dist-upgrade && \
  DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
  fontconfig \
  unzip \
  wget \
  git \
  git-lfs \
  openssh-client \
  vim \
  && apt-get clean \
  && rm -rf /var/cache/apt/archives/* \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
  && truncate -s 0 /var/log/*log

RUN mkdir /app && mkdir /dotgradle
WORKDIR /app
# download dependencies
COPY . .
RUN ./gradlew build -x test --continue
RUN ./gradlew build
RUN cp $(./gradlew outgoingVariants --variant bootArchives | grep artifactType | awk '{print $2}') /app/myapp.jar

# https://snyk.io/blog/docker-for-java-developers/
# https://github.com/keeganwitt/docker-gradle/blob/e1e5d8d814938022d495bf76d74ebc945412eb0a/hotspot/jre11/Dockerfile

FROM adoptopenjdk:11-jre-openj9-focal

ARG USER
ARG USERID

RUN apt-get update -qq && \
  DEBIAN_FRONTEND=noninteractive apt-get -yq dist-upgrade && \
  apt-get clean && \
  rm -rf /var/cache/apt/archives/* && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
  truncate -s 0 /var/log/*log
RUN set -o errexit -o nounset \
  && echo "Adding internal user and group" \
  && groupadd --system --gid $USERID $USER \
  && useradd --system --gid $USERID --uid $USERID --shell /bin/bash --create-home $USER \
  && ln -s /dotgradle /home/$USER/.gradle \
  && chown --recursive $USER:$USER /home/$USER
RUN mkdir /app
WORKDIR /app
COPY --from=builder /app/myapp.jar .
EXPOSE 8080
RUN chown -R $USERID:$USERID /app
USER $USERID
CMD ["java", "-jar", "myapp.jar"]
