FROM adoptopenjdk:11-jdk-openj9-focal as build

ARG USER
ARG USERID

RUN apt-get update -qq && \
  DEBIAN_FRONTEND=noninteractive apt-get -yq dist-upgrade && \
  DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
  fontconfig \
  unzip \
  wget \
  git \
  git-lfs \
  openssh-client \
  vim \
  && apt-get clean \
  && rm -rf /var/cache/apt/archives/* \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
  && truncate -s 0 /var/log/*log

RUN mkdir /app && mkdir /dotgradle
RUN \
  set -o errexit -o nounset \
  && echo "Adding internal user and group" \
  && groupadd --system --gid $USERID $USER \
  && useradd --system --gid $USERID --uid $USERID --shell /bin/bash --create-home $USER \
  && ln -s /dotgradle /home/$USER/.gradle \
  && chown --recursive $USER:$USER /home/$USER
WORKDIR /app
RUN chown -R $USERID:$USERID /app
USER $USERID
CMD tail -f /dev/null
